# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            '<a href="http://www.affordablehvac.com">Affordable Heating & Air Conditioning</a>'
tagline:          "Where Quality and Integrity Meet...  It's Not Cheap It's Affordable!"
description:      'Greeley: 970-352-2820<br/>
                   Ft. Collins: 970-223-1433<br/>
                   Text: 970-301-0356<br/>
                   <a href="mailto:affordablehvac@gmail.com">affordablehvac@gmail.com</a>'
url:              http://www.affordablehvac.com
baseurl:          /

author:
  name:           'Russel Griffin'
  url:            http://www.affordablehvac.com

paginate:         5
