# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Affordable Heating & Air Conditioning
tagline:          "Where Quality and Integrity Meet...  It's Not Cheap It's Affordable!"
description:      'Greeley: 970-352-2820 <br/>Ft. Collins: 970-223-1433 <br/>Text: 970-301-0356'
url:              http://www.affordablehvac.com
