# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Affordable Heating & Air Conditioning
tagline:          'Where Quality and Integrity Meet'
description:      "Where Quality and Integrity Meet...  It's Not Cheap It's Affordable!"
url:              http://affordablehvac.com
