# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "Affordable Heating & Air Conditioning"
tagline:          "Where Quality and Integrity Meet...  It's Not Cheap It's Affordable!"
description:      'Affordable Heating & Air Conditioning installation, service and repair'
url:              http://www.affordablehvac.com
baseurl:          /

author:
  name:           'Russel Griffin'
  url:            http://www.affordablehvac.com

paginate:         5
